pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    def getNodeExecutable = {
        // 1. Intentar obtenerlo de una propiedad de Gradle (si se definió en gradle.properties)
        if (providers.gradleProperty('nodeExecutable').isPresent()) {
            return providers.gradleProperty('nodeExecutable').get()
        }
        // 2. Intentar buscarlo en el sistema (funciona si se abre desde terminal o hay enlace simbólico)
        def command = org.apache.tools.ant.taskdefs.condition.Os.isFamily(org.apache.tools.ant.taskdefs.condition.Os.FAMILY_WINDOWS) ? "where node" : "which node"
        try {
            def proc = command.execute()
            proc.waitFor()
            if (proc.exitValue() == 0) return proc.text.trim()
        } catch (Exception e) { }

        // 3. Fallback: Rutas comunes en macOS/Linux (incluyendo NVM por defecto)
        return "node"
    }
    def nodeExecutable = getNodeExecutable()

    def reactNativeGradlePluginPath = [
        nodeExecutable,
        "--print",
        "require.resolve('@react-native/gradle-plugin/package.json')"
    ].execute(null, rootDir).text.trim()

    includeBuild(new File(reactNativeGradlePluginPath).parentFile)
}

/* =========================================================
 *  Project
 * ========================================================= */
rootProject.name = "napp-app-protecta-security"

/* =========================================================
 *  Dependency resolution
 * ========================================================= */
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)

    repositories {
        google()
        mavenCentral()

        maven { url "https://maven.regulaforensics.com/RegulaDocumentReader" }
        maven { url "https://repo.zytrust.com/artifactory/zy-mobile-maven" }

        maven {
            url "https://identy.jfrog.io/identy/identy-face-release"
            credentials {
                username = "zytrust"
                password = "yK54WHqgel8PztBHwXZn7"
            }
        }
    }
}

/* =========================================================
 *  Expo & React Native autolinking (OFICIAL)
 * ========================================================= */
apply from: "../node_modules/expo/scripts/autolinking.gradle"
useExpoModules()

apply from: "../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"
applyNativeModulesSettingsGradle(settings)

/* =========================================================
 *  Modules
 * ========================================================= */
include(":app")
